// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ilzejhxsfcaiidzqocag.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlsemVqaHhzZmNhaWlkenFvY2FnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5Njg4ODYsImV4cCI6MjA3MTU0NDg4Nn0.6qGNDXqWGiZJahRL88Ypcaj9wsLK3L2vhcJEJgTRBQM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});